accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_user, name="login"),
    path('register/', views.register, name="register"),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.posts, name="posts"),
    path('create-post/', views.create_post, name="create-post"),
    path('edit-post/<str:pk>/', views.edit_post, name="edit-post"),
    path('delete-post/<str:pk>/', views.delete_post, name="delete-post"),
]

sitio_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='posts', null=True)
    image = models.ImageField(null=True)
    likes = models.PositiveIntegerField(default=0, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    quote = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.quote


class Comment(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='comments', null=True)
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="comments", null=True)
    text = models.TextField()

posts/forms.py
from .models import Post, Comment
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('quote', 'image')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['quote'].widget.attrs.update({"class": "form-control"})


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

accounts/views.py
from django.shortcuts import render


def register(request):
    return render(request, 'accounts/register.html')


def login_user(request):
    return render(request, 'accounts/login.html')

home/views.py
from django.shortcuts import render

def home(request):
    return render (request, 'home.html')

# Create your views here.

posts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Post, Comment
from .forms import PostForm, CommentForm


def posts(request):
    posts = Post.objects.all().order_by('-created_at')
    return render(request, 'posts/posts.html', {"posts": posts})


def create_post(request):
    form = PostForm()

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)

        if form.is_valid():
            post = form.save()
            return redirect("posts:posts")

    return render(request, 'posts/create_post.html', {"form": form})


def edit_post(request, pk):
    post = Post.objects.get(id=pk)
    form = PostForm(instance=post)

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)

        if form.is_valid():
            form.save()
            return redirect("posts:posts")

    return render(request, 'posts/create_post.html', {'form': form})


def delete_post(request, pk):
    post = Post.objects.get(id=pk)

    if request.method == "POST":
        post.delete()
        return redirect("posts:posts")

    return render(request, 'posts/delete_post.html', {'post': post})

accounts/templates/accounts/login.html
{% extends 'base.html' %} 

{% block content %}
<h1>Login</h1>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %} 

{% block content %}
<h1>Register</h1>
{% endblock %}

home/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CAMPESTRE D</title>
    <link rel="shortcut icon" href="{% static 'images/arbol.png' %}"" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>

<body>
    <header class="header">
        <section class="logo">
            <img src="" alt="">
            <span>CAMPESTRE D</span>
        </section>
        <section class="menu-opciones">
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="/posts">Servicio Zoocial</a></li>
                <li><a href="/posts">Cuidados Ambientales</a></li>
                <li><a href="posts">Centro Deportivo</a></li>
                <li><a href="/posts">Feria Micro-empresarial</a></li>
                <li><a href="/posts">Afiliados</a></li>

            </ul>
        </section>
        <section class="controles-usuarios">
            <ion-icon name="search-sharp"></ion-icon>
            <button id="btn-sign-up"></button>
        </section>
        </div>
        </div>
        <section class="text-header">
            <h1>CAMPESTRE D</h1>
            <h1>La naturaleza nunca se apresura, y sin embargo, todo se logra</h1>
        </section>
        <div class="wave" style="height: 150px; overflow: hidden;"><svg viewBox="0 0 500 150" preserveAspectRatio="none"
                style="height: 100%; width: 100%;">
                <path d="M-0.00,49.87 C150.00,149.67 349.21,-49.87 500.00,49.87 L500.00,149.67 L-0.00,149.67 Z"
                    style="stroke: none; fill: rgb(255, 255, 255);"></path>
            </svg></div>
    </header>
    <main>
        <section class="contenedor sobre-nosotros">
            <h2 class="titulo">Nuestros Proyectos</h2>
            <div class="contenedor-sobre-nosotros">
                <img src="{% static 'images/fondo1.jpeg' %}"" alt="" class="imagen-about-us">
                <div class="contenido-texto">
                    <h3><span>1</span>Servicio Zoocial</h3>
                    <p>Representamos a la comunidad generando un apoyo del cual los peluditos se pueden beneficiar en el entorno en el que se encuentran. 
                    </p>
                    <h3><span>2</span>Servicio Ambiental</h3>
                    <p>Representamos el orden y el cuidado del medio ambiente en el sector, creando así un ambiente amigable y un lugar seguro para todos</p>
                    <h3><span>3</span>Servicio MicroEmpresarial</h3>
                    <p>Fomentamos el comercio en nuestra comunidad con el fin de dar a conocer los negocios locales y ayudarlos a crecer</p>

                </div>
            </div>
        </section>
        <section class="portafolio">
            <div class="contenedor">
                <h2 class="titulo">Comunidad</h2>
                <div class="galeria-portafolio">
                    <div class="imagen-portafolio">
                        <img src="{% static 'images/-1.jpg' %}" alt="">
                        <div class="hover-galeria">
                            <img src="logo.jpg" alt="">
                            <p>Servicios Ambientales</p>
                        </div>
                    </div>
                    <div class="imagen-portafolio">
                        <img src="{% static 'images/-2.jpg' %}" alt="">
                        <div class="hover-galeria">
                            <img src="logo.jpg" alt="">
                            <p>Cuidado de peluditos</p>
                        </div>
                    </div>
                    <div class="imagen-portafolio">
                        <img src="{% static 'images/-3.jpg' %}" alt="">
                        <div class="hover-galeria">
                            <img src="logo.jpg" alt="">
                            <p>Limpienza</p>
                        </div>
                    </div>
                    <div class="imagen-portafolio">
                        <img src="{% static 'images/-4.jpg' %}" alt="">
                        <div class="hover-galeria">
                            <img src="logo.jpg" alt="">
                            <p>Amor</p>
                        </div>
                    </div>
                    <div class="imagen-portafolio">
                        <img src="{% static 'images/-5.jpg' %}" alt="">
                        <div class="hover-galeria">
                            <img src="logo.jpg" alt="">
                            <p>Amistad</p>
                        </div>
                    </div>
                    <div class="imagen-portafolio">
                        <img src="{% static 'images/-6.jpg' %}" alt="">
                        <div class="hover-galeria">
                            <img src="logo.jpg" alt="">
                            <p>Tolerancia</p>
                        </div>
                    </div>
                    <div class="imagen-portafolio">
                        <img src="{% static 'images/-7.jpg' %}" alt="">
                        <div class="hover-galeria">
                            <img src="logo.jpg" alt="">
                            <p>Alegria</p>
                        </div>
                    </div>
                    <div class="imagen-portafolio">
                        <img src="{% static 'images/-8.jpg' %}" alt="">
                        <div class="hover-galeria">
                            <img src="logo.jpg" alt="">
                            <p>Hogar</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="clientes contenedor">
            <h2 class="titulo">Representantes de la junta de acción comunal</h2>
            <div class="cards">
                <div class="card">
                    <img src="{% static 'images/perfil1.jpg' %}" alt="">
                    <div class="contenido-texto-cards">
                        <h4>Orlando</h4>
                        <p>Representante de la comunidad (Presidente) y de la junta de acción comunal</p>
                    </div>
                </div>
                <div class="card">
                    <img src="{% static 'images/perfil2.jpg' %}" alt="">
                    <div class="contenido-texto-cards">
                        <h4>Edwin</h4>
                        <p>Representante de la comunidad (Vicepresidente) segundo al mando</p>
                    </div>
                </div>
            </div>
        </section>
        <section class="about-services">
            <div class="contenedor">
                <h2 class="titulo">Nuestros aportes a la comunidad</h2>
                <div class="servicio-contenedor">
                    <div class="servicio-individual">
                        <img src="Fondo.jpg" alt="">
                        <h4>Cuidados Ambientales</h4>
                        <p>Nuestro servicio se enfoca en procurar un ambiente agradable y sano, garantizando la seguridad de la comunidad.</p>
                    </div>
                    <div class="servicio-individual">
                        <img src="Fondo.jpg" alt="">
                        <h4>Servicio Zoocial</h4>
                        <p>Ayudamos a los peluditos a conseguir un hogar, proporcionándoles un lugar agradable, la comida necesaria y garantizando un entorno saludable para ellos.</p>
                    </div>
                    <div class="servicio-individual">
                        <img src="Fondo.jpg" alt="">
                        <h3>Micro-empresas</h3>
                        <p>Garantizamos el comercio de nuestra comunidad, para fomentar el crecimiento industrial.</p>
                    </div>
                </div>
            </div>
        </section>
        <footer>
            <div class="contenedor-footer">
                <div class="contentenido-footer">
                    <h4>Phone-1</h4>
                    <p>3182375392</p>
                </div>
                <div class="contentenido-footer">
                    <h4>Phone-2</h4>
                    <p>3116186263</p>
                </div>
                <div class="contentenido-footer">
                    <h4>Email</h4>
                    <p>camprested@gmail.com</p>
                </div>
                <div class="contentenido-footer">
                    <h4>Location</h4>
                    <p>Cra. 8 #20a-23, Dosquebradas - Campestre D</p>
                </div>
            </div>
            <h2 class="titulo-final">&copy; Jorge Alejandro | Campestre D</h2>
        </footer>
    </main>
</body>

</html>

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block content %}
{% include 'navbar.html' %}

<div class="profile-form-container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary mt-2">Submit</button>
    </form>
</div>

{% endblock %}

posts/templates/posts/delete_post.html
{% extends 'base.html' %}
{% block content %}
{% extends 'base.html' %}
{% block content %}
{% include 'navbar.html' %}

<div class="profile-form-container">
    <h5 class="card-title">Delete Post?</h5>
    <p class="card-text">Deleting a post will permanently delete it from the database.</p>
    <form method="POST" action="{% url 'posts:delete-post' post.pk %}">
        {% csrf_token %}
        <a class="btn btn-primary" href="{% url 'posts:posts' %}">Keep Post</a>
        <button type="submit" class="btn btn=primary mt-2">Delete Post</button>
    </form>

</div>

{% endblock %}

posts/templates/posts/posts.html
{% extends 'base.html' %}
{% load static %}
    
{% block content %}
{% include 'navbar.html' %}

<div class="post-container">
    {% for post in posts %}
        <div class="post">
            <div class="post-header d-flex justify-content-between">
                <div class="d-flex">
                    <a href="#">
                        <img class="profile-pic" src="{% static 'images/default_pic.jpg' %}">
                    </a>
                    <h6 class="post-user">{{post.user.username}}</h6>
                </div>
                <ul class="navbar-nav justify-content-end">
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-ellipsis-h" style="color: gray;"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'posts:edit-post' post.pk %}">Edit</a>
                              <a class="dropdown-item" href="{% url 'posts:delete-post' post.pk %}">Delete</a>
                              <a class="dropdown-item" href="#">Go to post</a>
                              <a class="dropdown-item" href="#">Go to post</a>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="post-pic-container">
                <img class="post-pic" src="{{post.image.url}}">
            </div>
            <div class="post-footer">
                <div class="likes d-flex">
                    <a href="#"><i class="far fa-heart fa-lg mr-1 mt-1" style="color: black;"></i></a>
                    <p><strong>{{post.likes}} likes</strong></p>
                </div>
                <p class="quote"><strong>{{post.user.username}}</strong> {{post.quote}}</p>
                <a href="#"><p class="test-muted">See the {{post.comments.all.count}} comments</p></a>
                <small class="test-muted">{{post.created_at|date:"M d, Y"}}</small>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="https://kit.fontawesome.com/1b2de11c6b.js" crossorigin="anonymous"></script>
</head>
<body>
    {% block content %}

    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-white">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">CAMPESTRE D</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav w-100 justify-content-end">
        <li class="nav-item">
          <a class="plus-link" aria-current="page" href="{% url 'posts:create-post' %}">+</a>
        </li>
        <li class="nav-item">
          <img class="profile-pic" src="" alt="Profile Pic">
      </ul>
    </div>
  </div>
</nav>